export const dropdownFoodData = [
    { text: "Cherry", value: 1, category: "Fruit", active: true, price: 2.5, origin: "Local" },
    { text: "Cabbage", value: 2, category: "Vegetable", active: true, price: 1.2, origin: "Local" },
    { text: "Grilled Meat", value: 3, category: "Food", active: true, price: 8.0, origin: "Imported" },
    { text: "Plum", value: 4, category: "Fruit", active: true, price: 2.0, origin: "Local" },
    { text: "Banana", value: 5, category: "Fruit", active: true, price: 1.5, origin: "Imported" },
    { text: "Cabbage Black", value: 6, category: "Vegetable", active: true, price: 1.5, origin: "Local" },
    { text: "Quince", value: 7, category: "Fruit", active: true, price: 3.0, origin: "Local" },
    { text: "Pineapple", value: 8, category: "Fruit", active: true, price: 4.0, origin: "Imported" },
    { text: "Pumpkin", value: 9, category: "Vegetable", active: false, price: 2.8, origin: "Local" },
    { text: "Peach", value: 10, category: "Fruit", active: false, price: 2.7, origin: "Local" },
    { text: "Pear", value: 11, category: "Fruit", active: true, price: 2.3, origin: "Local" },
    { text: "Pomegranate", value: 12, category: "Fruit", active: true, price: 3.5, origin: "Imported" },
    { text: "Paprika", value: 13, category: "Vegetable", active: true, price: 1.8, origin: "Imported" },
    { text: "Potato", value: 14, category: "Vegetable", active: false, price: 1.0, origin: "Local" },
    { text: "Raspberry", value: 15, category: "Fruit", active: true, price: 3.8, origin: "Local" },
    { text: "Strawberry", value: 16, category: "Fruit", active: true, price: 3.2, origin: "Local" },
    { text: "Tomato", value: 17, category: "Vegetable", active: true, price: 2.0, origin: "Local" },
    { text: "Watermelon", value: 18, category: "Fruit", active: true, price: 5.0, origin: "Imported" },
    { text: "Zucchini", value: 19, category: "Vegetable", active: true, price: 1.7, origin: "Local" },
    { text: "Apple", value: 20, category: "Fruit", active: true, price: 2.2, origin: "Local" },
    { text: "Apricot", value: 21, category: "Fruit", active: true, price: 2.6, origin: "Local" },
    { text: "Yakisoba", value: 22, category: "Food", active: true, price: 7.5, origin: "Imported" },
    { text: "Yakitori", value: 23, category: "Food", active: true, price: 6.0, origin: "Imported" },
    { text: "Sushi", value: 24, category: "Food", active: false, price: 10.0, origin: "Imported" },
    { text: "Sashimi", value: 25, category: "Food", active: true, price: 12.0, origin: "Imported" },
    { text: "Soba", value: 26, category: "Food", active: false, price: 7.0, origin: "Imported" },
    { text: "Ramen", value: 27, category: "Food", active: true, price: 8.5, origin: "Imported" },
    { text: "Onigiri", value: 28, category: "Food", active: true, price: 3.0, origin: "Imported" },
    { text: "Okonomiyaki", value: 29, category: "Food", active: true, price: 9.0, origin: "Imported" },
    { text: "Yakizakana", value: 30, category: "Food", active: true, price: 11.0, origin: "Imported" },
    { text: "Pink-flowered native raspberry", value: 31, category: "Fruit", active: true, price: 4.2, origin: "Local" }
];
