import type { ChartHierarchyPointMetadata } from "./chart-hierarchy.models";
import type { ChartFinancialDirection } from "./chart-financial.models";
import type { ChartOhlcPointValue, ChartPointValueKind } from "./chart-point-value.models";
import type { ChartSeriesType } from "./chart-series.models";
import type { ChartStackMode } from "./chart-stack.models";

export interface ChartPointEvent<T = unknown> {
    category?: unknown;
    categoryX?: string;
    categoryY?: string;
    change?: number;
    changePercentage?: number;
    close?: number;
    dataIndex: number;
    datum: T;
    financial?: ChartOhlcPointValue;
    financialDirection?: ChartFinancialDirection;
    formattedChange?: string;
    formattedChangePercentage?: string;
    formattedClose?: string;
    formattedFrom?: string;
    formattedHigh?: string;
    formattedLow?: string;
    formattedOpen?: string;
    formattedTo?: string;
    formattedXValue?: string;
    formattedYCategory?: string;
    fromValue?: number;
    hierarchy?: ChartHierarchyPointMetadata;
    high?: number;
    low?: number;
    open?: number;
    percentage?: number;
    rawValue?: unknown;
    seriesId: string;
    seriesName: string;
    seriesType: ChartSeriesType;
    sizeValue?: number;
    sliceId?: string;
    stackEnd?: number;
    stackGroup?: string;
    stackMode?: ChartStackMode;
    stackPercentage?: number;
    stackPosition?: "inner" | "outer" | "single";
    stackStart?: number;
    stackTotal?: number;
    toValue?: number;
    valueKind?: ChartPointValueKind;
    xValue: unknown;
    yCategory?: unknown;
    yValue?: number;
}

export interface ChartPointFocusEvent<T = unknown> {
    category?: unknown;
    categoryX?: string;
    categoryY?: string;
    change?: number;
    changePercentage?: number;
    close?: number;
    dataIndex: number;
    datum: T;
    financial?: ChartOhlcPointValue;
    financialDirection?: ChartFinancialDirection;
    formattedChange?: string;
    formattedChangePercentage?: string;
    formattedClose?: string;
    formattedFrom?: string;
    formattedHigh?: string;
    formattedLow?: string;
    formattedOpen?: string;
    formattedTo?: string;
    formattedXValue?: string;
    formattedYCategory?: string;
    fromValue?: number;
    hierarchy?: ChartHierarchyPointMetadata;
    high?: number;
    low?: number;
    open?: number;
    percentage?: number;
    rawValue?: unknown;
    seriesId: string;
    seriesName: string;
    seriesType: ChartSeriesType;
    sizeValue?: number;
    sliceId?: string;
    stackEnd?: number;
    stackGroup?: string;
    stackMode?: ChartStackMode;
    stackPercentage?: number;
    stackPosition?: "inner" | "outer" | "single";
    stackStart?: number;
    stackTotal?: number;
    toValue?: number;
    valueKind?: ChartPointValueKind;
    xValue: unknown;
    yCategory?: unknown;
    yValue?: number;
}

export interface ChartSeriesVisibilityEvent {
    seriesId: string;
    seriesName: string;
    visible: boolean;
}
