export {
    createWindowStyleStrategy,
    windowBaseThemeVariants,
    windowContentContainerThemeVariants,
    windowContentThemeVariants,
    windowResizerThemeVariants,
    windowTitleBarActionThemeVariants,
    windowTitleBarThemeVariants,
    windowTitleContainerThemeVariants,
    windowTitleThemeVariants
} from "./window.style-strategy";
export { provideWindowStyles, WINDOW_STYLE_OVERRIDES, WINDOW_STYLE_STRATEGY } from "./window.style-provider";
export type {
    WindowBaseCompoundStyleOverride,
    WindowBaseStyleOverrides,
    WindowBaseVariantInput,
    WindowBaseVariantProps,
    WindowContentContainerCompoundStyleOverride,
    WindowContentContainerStyleOverrides,
    WindowContentContainerVariantInput,
    WindowContentContainerVariantProps,
    WindowContentStyleOverrides,
    WindowContentVariantInput,
    WindowContentVariantProps,
    WindowResizerCompoundStyleOverride,
    WindowResizerStyleOverrides,
    WindowResizerVariantInput,
    WindowResizerVariantProps,
    WindowStyleOverrides,
    WindowStylesProviderConfig,
    WindowStyleStrategy,
    WindowTitleBarActionStyleOverrides,
    WindowTitleBarActionVariantInput,
    WindowTitleBarActionVariantProps,
    WindowTitleBarCompoundStyleOverride,
    WindowTitleBarStyleOverrides,
    WindowTitleBarVariantInput,
    WindowTitleBarVariantProps,
    WindowTitleCompoundStyleOverride,
    WindowTitleContainerStyleOverrides,
    WindowTitleContainerVariantInput,
    WindowTitleContainerVariantProps,
    WindowTitleStyleOverrides,
    WindowTitleVariantInput,
    WindowTitleVariantProps,
    WindowVariantInput,
    WindowVariantProps,
    WindowVariantsFunctions
} from "./window.types";
