export {
    createDialogStyleStrategy,
    dialogBaseThemeVariants,
    dialogBodyThemeVariants,
    dialogCloseButtonContainerThemeVariants,
    dialogContentContainerThemeVariants,
    dialogContentThemeVariants,
    dialogDescriptionThemeVariants,
    dialogFooterThemeVariants,
    dialogHeaderThemeVariants,
    dialogIconContainerThemeVariants,
    dialogIconThemeVariants,
    dialogTitleContainerThemeVariants,
    dialogTitleThemeVariants
} from "./dialog.style-strategy";
export { DIALOG_STYLE_OVERRIDES, DIALOG_STYLE_STRATEGY, provideDialogStyles } from "./dialog.style-provider";
export type {
    DialogBaseCompoundStyleOverride,
    DialogBaseStyleOverrides,
    DialogBaseVariantInput,
    DialogBaseVariantProps,
    DialogBodyCompoundStyleOverride,
    DialogBodyStyleOverrides,
    DialogBodyVariantProps,
    DialogCloseButtonContainerStyleOverrides,
    DialogContentContainerStyleOverrides,
    DialogContentContainerVariantProps,
    DialogContentStyleOverrides,
    DialogContentVariantProps,
    DialogDescriptionStyleOverrides,
    DialogDescriptionVariantProps,
    DialogFooterCompoundStyleOverride,
    DialogFooterStyleOverrides,
    DialogFooterVariantProps,
    DialogHeaderStyleOverrides,
    DialogHeaderVariantProps,
    DialogIconCompoundStyleOverride,
    DialogIconContainerStyleOverrides,
    DialogIconContainerVariantInput,
    DialogIconContainerVariantProps,
    DialogIconStyleOverrides,
    DialogIconVariantInput,
    DialogIconVariantProps,
    DialogStyleOverrides,
    DialogStylesProviderConfig,
    DialogStyleStrategy,
    DialogTitleContainerStyleOverrides,
    DialogTitleContainerVariantProps,
    DialogTitleStyleOverrides,
    DialogTitleVariantProps,
    DialogVariantInput,
    DialogVariantProps,
    DialogVariantsFunctions
} from "./dialog.types";
