import type { ThemeColors, ThemeDefinition } from "../models/ThemeDefinition";
import { generateThemeColorPalette } from "../utils/generate-theme-color-palette";

const generatedRoles = generateThemeColorPalette({
    primary: "#7486ff",
    secondary: "#a874ff",
    success: "#36b37e",
    error: "#e45778",
    warning: "#d99426",
    info: "#3b9eea"
});

const light: ThemeColors = Object.freeze({
    "--color-canvas": "oklch(96.5% 0.025 275)",
    "--color-surface": "oklch(98.6% 0.012 275)",
    "--color-surface-muted": "oklch(94.5% 0.025 275)",
    "--color-surface-raised": "oklch(98% 0.018 275)",
    "--color-surface-overlay": "oklch(98.8% 0.014 275)",
    "--color-foreground": "oklch(22% 0.035 272)",
    "--color-muted-foreground": "oklch(48% 0.035 272)",
    "--color-input-background": "oklch(97.5% 0.02 275)",
    "--color-input-foreground": "var(--color-foreground)",
    "--color-border-subtle": "oklch(88% 0.04 275)",
    "--color-border": "oklch(64.5% 0.07 275)",
    "--color-border-control": "oklch(62% 0.08 275)",
    "--color-border-control-hover": "oklch(55% 0.12 275)",
    "--color-hover": "oklch(92.5% 0.045 275)",
    "--color-active": "oklch(87% 0.07 275)",
    "--color-disabled-foreground": "oklch(52% 0.025 275)",
    "--color-disabled-background": "oklch(93.5% 0.018 275)",
    "--color-disabled-border": "oklch(86% 0.025 275)",
    ...generatedRoles.light,
    "--color-selected": "var(--color-primary-subtle)",
    "--color-selected-foreground": "var(--color-primary-subtle-foreground)",
    "--color-selected-hover": "var(--color-accent-hover)",
    "--color-selected-hover-foreground": "var(--color-primary-subtle-foreground)",
    "--color-selected-active": "var(--color-accent-active)",
    "--color-selected-active-foreground": "var(--color-primary-subtle-foreground)",
    "--color-selected-focus": "var(--color-accent-hover)",
    "--color-selected-focus-foreground": "var(--color-primary-subtle-foreground)",
    "--color-selected-border": "var(--color-primary-border)",
    "--color-focus-surface": "var(--color-primary-subtle)",
    "--color-background": "var(--color-surface)",
    "--color-background-dark": "var(--color-surface-muted)",
    "--color-header-background": "var(--color-surface-muted)",
    "--color-header-foreground": "var(--color-foreground)",
    "--color-input-border": "var(--color-border-control)",
    "--color-input-hover": "var(--color-hover)",
    "--color-input-active": "var(--color-surface-raised)",
    "--color-popover": "var(--color-surface-overlay)",
    "--color-popover-foreground": "var(--color-foreground)",
    "--color-muted": "var(--color-surface-muted)",
    "--color-destructive": "var(--color-error)",
    "--color-destructive-foreground": "var(--color-error-foreground)",
    "--color-input": "var(--color-border-control)",
    "--color-disabled": "var(--color-disabled-foreground)",
    "--color-chart-1": "#7486ff",
    "--color-chart-2": "#a874ff",
    "--color-chart-3": "#4fb5e9",
    "--color-chart-4": "#54c9a4",
    "--color-chart-5": "#e690b0",
    "--color-scrollbar-thumb": "oklch(72% 0.06 275)",
    "--color-scrollbar-thumb-hover": "oklch(62% 0.1 275)",
    "--color-scrollbar-thumb-active": "oklch(54% 0.14 275)",
    "--color-scrollbar-thumb-focus": "var(--color-focus-indicator)",
    "--color-scrollbar-track": "var(--color-canvas)",
    "--color-scrollbar-track-hover": "var(--color-surface-muted)",
    "--color-scrollbar-track-active": "var(--color-hover)",
    "--color-scrollbar-track-focus": "var(--color-accent)",
    "--color-scrollbar-corner": "var(--color-canvas)"
});

const dark: ThemeColors = Object.freeze({
    "--color-canvas": "oklch(13% 0.025 275)",
    "--color-surface": "oklch(17% 0.03 275)",
    "--color-surface-muted": "oklch(21% 0.035 275)",
    "--color-surface-raised": "oklch(24% 0.04 275)",
    "--color-surface-overlay": "oklch(27% 0.045 275)",
    "--color-foreground": "oklch(96.5% 0.012 275)",
    "--color-muted-foreground": "oklch(75% 0.03 275)",
    "--color-input-background": "oklch(21% 0.035 275)",
    "--color-input-foreground": "var(--color-foreground)",
    "--color-border-subtle": "oklch(29% 0.045 275)",
    "--color-border": "oklch(55% 0.08 275)",
    "--color-border-control": "oklch(58% 0.09 275)",
    "--color-border-control-hover": "oklch(66% 0.12 275)",
    "--color-hover": "oklch(29% 0.055 275)",
    "--color-active": "oklch(37% 0.085 275)",
    "--color-disabled-foreground": "oklch(64% 0.025 275)",
    "--color-disabled-background": "oklch(23% 0.025 275)",
    "--color-disabled-border": "oklch(31% 0.035 275)",
    ...generatedRoles.dark,
    "--color-selected": "var(--color-accent)",
    "--color-selected-foreground": "var(--color-accent-foreground)",
    "--color-selected-hover": "var(--color-accent-hover)",
    "--color-selected-hover-foreground": "var(--color-accent-foreground)",
    "--color-selected-active": "var(--color-accent-active)",
    "--color-selected-active-foreground": "var(--color-accent-foreground)",
    "--color-selected-focus": "var(--color-accent-hover)",
    "--color-selected-focus-foreground": "var(--color-accent-foreground)",
    "--color-selected-border": "var(--color-primary-border)",
    "--color-focus-surface": "var(--color-accent)",
    "--color-background": "var(--color-surface)",
    "--color-background-dark": "var(--color-surface-muted)",
    "--color-header-background": "var(--color-surface-muted)",
    "--color-header-foreground": "var(--color-foreground)",
    "--color-input-border": "var(--color-border-control)",
    "--color-input-hover": "var(--color-hover)",
    "--color-input-active": "var(--color-surface-raised)",
    "--color-popover": "var(--color-surface-overlay)",
    "--color-popover-foreground": "var(--color-foreground)",
    "--color-muted": "var(--color-surface-muted)",
    "--color-destructive": "var(--color-error)",
    "--color-destructive-foreground": "var(--color-error-foreground)",
    "--color-input": "var(--color-border-control)",
    "--color-disabled": "var(--color-disabled-foreground)",
    "--color-chart-1": "#9aa7ff",
    "--color-chart-2": "#c59aff",
    "--color-chart-3": "#72cbf3",
    "--color-chart-4": "#72ddb9",
    "--color-chart-5": "#f1a4bf",
    "--color-scrollbar-thumb": "oklch(43% 0.065 275)",
    "--color-scrollbar-thumb-hover": "oklch(55% 0.1 275)",
    "--color-scrollbar-thumb-active": "oklch(68% 0.13 275)",
    "--color-scrollbar-thumb-focus": "var(--color-focus-indicator)",
    "--color-scrollbar-track": "var(--color-canvas)",
    "--color-scrollbar-track-hover": "var(--color-surface-muted)",
    "--color-scrollbar-track-active": "var(--color-hover)",
    "--color-scrollbar-track-focus": "var(--color-accent)",
    "--color-scrollbar-corner": "var(--color-canvas)"
});

export const lunaThemeColors = Object.freeze({ light, dark } satisfies ThemeDefinition);
